//
//   Copyright 2024 R. Kent James <kent@caspia.com>
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

#ifndef DISABLE_BREATHE__TEST_NODE_HPP_
#define DISABLE_BREATHE__TEST_NODE_HPP_

/// @file
/// @brief This is an include file to go with the C++ file generated by `ros2 pkg create`

/**
  This demo program just prints hello world.
  */
int main(int argc, char ** argv)

#endif  // DISABLE_BREATHE__TEST_NODE_HPP_
